DEVICE_PATH := device/huawei/jakarta

# Architecture - 32-bit (ARM)
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := generic

# Kernel
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/kernel
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2
BOARD_KERNEL_PAGESIZE := 2048
BOARD_BOOTIMG_HEADER_VERSION := 2
BOARD_MKBOOTIMG_ARGS := --header_version $(BOARD_BOOTIMG_HEADER_VERSION)

# Platform
TARGET_BOARD_PLATFORM := mt6765
TARGET_BOOTLOADER_BOARD_NAME := jakarta
TARGET_NO_BOOTLOADER := true
TARGET_USES_64_BIT_BINDER := false

# Display
TARGET_SCREEN_DENSITY := 320
DEVICE_RESOLUTION := 720x1600

# Logical Partitions (Dynamic Partitions)
BOARD_MAIN_OTA_UPDATE_PACKAGE_SIZE := 4294967296
BOARD_SUPER_PARTITION_SIZE := 4294967296 
BOARD_SUPER_PARTITION_GROUPS := huawei_dynamic_partitions
BOARD_HUAWEI_DYNAMIC_PARTITIONS_PARTITION_LIST := system vendor product odm
BOARD_HUAWEI_DYNAMIC_PARTITIONS_SIZE := 4290772992

# File Systems
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_RECOVERY_CHARACTERISTICS := nosdcard
BOARD_USERDATAIMAGE_PARTITION_SIZE := 53687091200 # Based on your scatter (~54GB)
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_CACHEIMAGE_PARTITION_SIZE := 452984832
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true

# TWRP Specific Flags
TW_THEME := portrait_hdpi
TW_BRIGHTNESS_PATH := "/sys/class/leds/lcd-backlight/brightness"
TW_MAX_BRIGHTNESS := 255
TW_DEFAULT_BRIGHTNESS := 162
TW_EXTRA_LANGUAGES := true
TW_INCLUDE_NTFS_3G := true
TW_USE_TOOLBOX := true
TW_HAS_EDL_MODE := true
TW_NO_REBOOT_BOOTLOADER := true
TW_INCLUDE_REPACKTOOLS := true

# Encryption (Android 10 FBE)
PLATFORM_VERSION := 10
PLATFORM_SECURITY_PATCH := 2021-09-01
TW_INCLUDE_CRYPTO := true
TW_USE_FSCRYPT_POLICY := 2

# Hardware / Modules
TARGET_RECOVERY_DEVICE_MODULES := libion
RECOVERY_LIBRARY_SOURCE_FILES += $(TARGET_OUT_SHARED_LIBRARIES)/libion.so
